export const GET_COVER='GET_COVER'
export const UPDATE_COVER='UPDATE_COVER'
export const HIDE_SPLASH_SCREEN='HIDE_SPLASH_SCREEN'

export const FETCH_POST_LIST='FETCH_POST_LIST'
export const FETCH_LIKE_POST_LIST='FETCH_LIKE_POST_LIST'
export const FETCH_POST_DETAIL='FETCH_POST_DETAIL'
export const FETCH_POST_DETAIL_START='FETCH_POST_DETAIL_START'
export const ADD_POST='ADD_POST'
export const LIKE='LIKE'
export const LIKE_SUCCESS='LIKE_SUCCESS'
export const LIKE_FAIL='LIKE_FAIL'
export const UNLIKE='UNLIKE'
export const UNLIKE_SUCCESS='UNLIKE_SUCCESS'
export const UNLIKE_FAIL='UNLIKE_FAIL'

export const SET_SELECTED_TAB='SET_SELECTED_TAB'

export const FETCH_START='FETCH_START'
export const FETCH_FINISH='FETCH_FINISH'

export const FRESH_POST_START='FRESH_POST_START'
export const FRESH_POST_FINISH='FRESH_POST_FINISH'

export const FETCH_NEXT_PAGE_START='FETCH_NEXT_PAGE_START'
export const FETCH_NEXT_PAGE_FINISH='FETCH_NEXT_PAGE_FINISH'

export const ADD_COMMENT='ADD_COMMENT'
export const ADD_COMMENT_SUCCESS='ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAIL='ADD_COMMENT_FAIL'

export const ADD_POST_START='ADD_POST_START'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'

export const UPDATE_POST_START='UPDATE_POST_START'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const SELECTED_IMG='SELECTED_IMG'

