export const FETCH_POST_LIST='FETCH_POST_LIST'
export const FETCH_POST_DETAIL='FETCH_POST_DETAIL'
export const ADD_POST='ADD_POST'
export const LIKE='LIKE'
export const LIKE_SUCCESS='LIKE_SUCCESS'
export const LIKE_FAIL='LIKE_FAIL'
export const UNLIKE='UNLIKE'
export const UNLIKE_SUCCESS='UNLIKE_SUCCESS'
export const UNLIKE_FAIL='UNLIKE_FAIL'

export const SET_SELECTED_TAB='SET_SELECTED_TAB'

export const FETCH_START='FETCH_START'
export const FETCH_FINISH='FETCH_FINISH'

export const FRESH_POST_START='FRESH_POST_START'
export const FRESH_POST_FINISH='FRESH_POST_FINISH'

export const ADD_COMMENT='ADD_COMMENT'
export const ADD_COMMENT_SUCCESS='ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAIL='ADD_COMMENT_FAIL'

